### ISSUE TITLE
[Chore] Setup CI/CD

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#8]
**Definition of Done**

- [x] https://github.com/tyrro/react-survey/issues/2

**Comment by malparty** [comment]
@tyrro should we split CI from CD? :) 
(I guess it depends a lot on what pipeline you would use too, so feel free to choose to not split it if that makes more sense in your context ;-) )

**Comment by tyrro** [comment]
Thanks for the comment @malparty!
I haven't given any thought to the implementation details till now. When I start working on this task, I might as well split it as you suggested!
